name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache-node
      with:
        path: |
          node_modules
          example/node_modules
        key: ${{ hashFiles('package.json', 'example/package.json') }}
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: YARN_IGNORE_PATH=1 yarn
      if: steps.cache-node.outputs.cache-hit != 'true'
    - run: YARN_IGNORE_PATH=1 yarn lint
    - run: YARN_IGNORE_PATH=1 yarn typecheck
    - run: YARN_IGNORE_PATH=1 yarn test --coverage
    - run: YARN_IGNORE_PATH=1 yarn prepare
